add map generation and display
esoviscode/discord-bot pull request #88
Opened 2023-01-20 11:45 UTC by gitesthuman

# Pull request review checklist 📝 ✅

This is a checklist that helps conduct a pull request review properly. These points are required to merge the PR

- [ ] There are no merge conflicts

- [ ] The pull request is named accordingly (description of the functionality - it
   will be visible in the changelog later)
   
- [ ] Every task requirement (from Jira) is done

- [ ] The app runs, it boots up properly (e.g. no syntax errors)

- [ ] The proposed functionality is working properly (you need to pull this branch
   and check for yourself)

- [ ] Each function, class or functionality is properly documented
   (short description of what it does, parameters or return values if they need
   any explanation)

2023-01-20 14:10 UTC, Silentsky0 commented
@gitesthuman trzeba dodać opencv-python do requirementsów

2023-01-21 10:56 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/prototype/entity.py
> +        self.fragile = fragile
@gitesthuman czym jest fragile?? że może zostać zniszczone czy że może się przesuwać

2023-01-21 14:29 UTC, Silentsky0 requested changes

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/prototype/entity.py
> +        self.fragile = fragile  # bool: if entity can be moved or destroyed from its position
this description should be in `:param:`

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +def paste_image(src: np.ndarray, dest: np.ndarray, x_offset: int, y_offset: int):
not documented

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    # print(f"game view processing time: {t} s")
delete useless comments

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    file_name = "dnd_bot/logic/utils/game_images/map%s.png" % game.token
you could use an fstring here

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    # print(f"player view processing time: {t} s")
useless comments

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +def get_player_view(game: Game, player: Player):
not documented

2023-01-21 14:29 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    file_name = "dnd_bot/logic/utils/game_images/pov%s_%s.png" % (game.token, player.discord_identity)
fstring here

2023-01-21 14:48 UTC, Silentsky0 commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    # print(f"game view processing time: {t} s")
useless comments

2023-01-21 14:52 UTC, gitesthuman commented on dnd-bot/dnd_bot/logic/utils/utils.py
> +    # print(f"game view processing time: {t} s")
needed for tests

2023-01-21 14:55 UTC, Silentsky0 approved these changes
LGTM

2023-01-21 14:55 UTC, merged